# 47. 에러 처리

### 47.1 에러 처리의 필요성

에러나 예외적인 상황에 대응하지 않으면 프로그램은 강제 종료되므로 대응하는 코드를 작성하는 것이 중요하다.

예외처리 구현은 크게 두가지가 있다.

1. querySelector나 Array#find 메서드처럼 예ㅚ적인 상황이 발생하면 반환하는 값을 if문이나 단축 평가 또는 옵셔널 체이닝 연산자를 통해 확인해 처리하는 방법
2. 에러 처리 코드를 미리 등록해 두고 에러가 발생하면 에러 처리 코드로 점프하도록 하는 방법

### 47.2 try … catch … finally 문

```jsx
try {
	foo();
} catch (err) {
	console.error(error);
} finally {
	console.log('finally');
}
```

try 블록에 포함된 문 중에서 에러가 발생하면 catch 코드블록 실행, finally는 에러 발생과 상관 없이 반드시 한 번 실행된다.

### 47.3 Error 객체

Error 생성자 함수는 에러 객체를 생성한다. Error 생성자 함수에는 에러를 상세히 설명하는 에러 메세지를 인수로 전달할 수 있다.

```jsx
const error = new Error('invalid');
```

| 생성자 함수 | 인스턴스 |
| --- | --- |
| Error | 일반적 에러 객체 |
| SyntaxError | 자바스크립트 문법에 맞지 않는 문을 해석할 때 발생 |
| ReferenceError | 참조할 수 없는 식별자를 참조했을 때 발생 |
| TypeError | 피연산자 또는 인수의 데이터 타입이 유효하지 않을 때 발생 |
| RangeError | 숫자값의 허용 범위를 벗어났을 때 발생 |
| URIError | encodeURI 또는 decodeURI 함수에 부적절한 인수를 전달했을 때 발생 |
| EvalError | eval 함수에서 발생 |

### 47.4 throw 문

Error 생성자 함수로 에러 객체를 생성한다고 에러가 발생하는 것은 아니다. 에러를 발생시키려면 try 코드 블록에서 throw 문으로 에러 객체를 던져야 한다.

### 47.5 에러의 전파

에러는 호출자 방향으로 전파된다. 즉 콜 스택의 아래 방향(실행 중인 실행 컨텍스트가 푸시되기 직전에 푸시된 실행 컨텍스트 방향)으로 전파된다.

throw된 에러를 캐치하지 않으면 호출자 방향으로 전파되는데 이때 에러를 적절히 캐치하여 대응하면 프로그램을 강제 종료시키지 않고 코드의 실행 흐름을 복구할 수 있다. throw 에러를 어디에서도 캐치하지 않으면 프로그램은 강제 종료된다.

비동기 함수인 setTimeout이나 프로미스 후속 처리 메서드의 콜백 함수는 호출자가 없어 에러를 전파할 호출자가 존재하지 않는다.