# 45. 프로미스

프로미스는 비동기 처리를 위해 ES6에서 도입, 전통적인 콜백 페턴이 가진 단점을 보완하며 비동기 처리 시점을 명확하게 표현할 수 있다는 장점이 있다.

### 45.1 비동기 처리를 위한 콜백 패턴의 단점

**45.1.1 콜백 헬**

비동기 함수를 호출하면 함수 내부의 비동기로 동작하는 코드가 완료되지 않았다 해도 기다리지 않고 즉시 종료된다. 즉 비동기 함수 내부의 비동기로 동작하는 코드는 비동기 함수가 종료된 이후에 완료된다. 따라서 비동기 함수 내부의 비동기로 동작하는 코드에서 처리 결과를 외부로 반환하거나 상위 스코프의 변수에 할당하면 기대한 대로 동작하지 않는다.

GET요청을 전송하고 서버의 응답을 받는 get 함수도 비 동기 함수이므로(get 내부의 onload 이벤트 핸들러가 비동기로 동작하기 때문) get 함수를 호출하면 GET 요청을 전송하고 onload 이벤트 핸들러를 등록한 다음 undefined로 반환하고 즉시 종료된다.

**비동기 함수는 비동기 처리 결과를 외부에 반환할 수 없고, 상위 스코프의 변수에 할당할 수도 없다. 따라서 비동기 함수 처리 결과(서버 응답 등)에 대한 후속 처리는 비동기 함수 내부에서 수행해야 한다. 이때 비동기 함수를 범용적으로 사용하기 위해 비동기 함수에 비동기 처리 결과에 대한 후속 처리를 수행하는 콜백 함수를 전달하는 것이 일반적이다. 필요에 따라 비동기 처리가 성공하면 호출될 콜백 함수와 비동기 처리가 실패하면 호출될 콜백 함수를 전달할 수 있다.**

```jsx
// GET 요청을 위한 비동기 함수
const get = (url, successCallback, failureCallback) => {
	const xhr = new XMLHttpRequest();
	xhr.open('GET', url);
	xhr.open();
	
	xhr.onload = () => {
		if (xhr.status === 200) {
			// 서버의 응답을 콜백 함수에 인수로 전달하면서 호출하여 응답에 대한 후속 처리
			successCallback(JSON.parse(xhr.response));
		} else {
			failureCallback(xhr.status);
		}
	};
};

// id가 1인 post 취득
// 서버의 응답에 대한 후속 처리를 위한 콜백 함수를 비동기 함수인 get에 전달
get('https://jsonplaceholder.typicode.com/posts/1', console.log, console.error);
```

이때 비동기 처리 결과에 대한 후속 처리를 수행하는 비동기 함수가 비동기 처리 결과를 가지고 또다시 비동기 함수를 호출해야 한다면… 콜백 함수 호출이 중첩되어 복잡도가 높아지는 현상이 발생하는데 이를 **콜백 헬**이라 한다.

**45.1.2 에러 처리의 한계**

```jsx
try {
	setTimeout(() => { throw new Error('Error!'); }, 1000);
} catch (e) {
	// 에러를 캐치하지 못함
	console.error('캐치한 에러', e);
}
```

비동기 함수인 setTimeout이 호출되면 setTimeout 함수의 실행 컨텍스트가 생성되어 콜 스택에 푸시되어 실행된다. setTimeout은 비동기 함수로 콜백 함수가 호출되는 것을 기다리지 않고 즉시 종료되어 콜 스택에서 제거된다. 이후 타이머가 만료되면 setTimeout 함수의 콜백 함수는 태스크 큐로 푸시되고 콜 스택이 비어졌을 때 이벤트 루프에 의해 콜 스택으로 푸시되어 실행된다.

setTimeout의 콜백 함수가 실행될 때 setTimeout 함수는 이미 콜 스택에 제거된 상태로 이는 setTimeout 콜백 함수를 호출한 것이 setTimeout 함수가 아니라는 것을 의미한다. setTimeout 함수의 콜백 함수 호출자가 setTimeout 함수라면 콜 스택의 현재 실행 중인 실행 컨텍스트가 콜백 함수의 실행 컨텍스트일 때 현재 실행중인 컨텍스트의 하위 실행 컨텍스트가 setTimeout 함수여야 한다. **에러는 호출자 방향으로 전파된다**. 즉 콜 스택 아래방향(실행 중인 실행 컨텍스트가 푸시되기 직전에 푸시된 실행 컨텍스트 방향)으로 전파된다. 하지만 setTimeout 함수의 콜백을 호출한 것은 setTimeout이 아니라 콜백함수가 발생시킨 에러는 catch 블록에서 캐치되지 않는다.

### 45.2 프로미스의 생성

Promise 생성자 함수를 new 연산자와 함께 호출하면 프로미스를 생성한다. ES6에서 도입된 Promise는 호스트 객체가 아닌 ECMAScript 사양에 정의된 표준 빌트인 객체다.

Promise 생성자 함수는 비동기 처리를 수행할 콜백 함수(executor)를 인수로 전달 받는데 이 콜백 함수는 resolve와 reject 함수를 인수로 전달받는다.

| 프로미스 상태 정보 | 의미 | 상태 변경 조건 |
| --- | --- | --- |
| pending | 비동기 처리가 아직 수행되지 않은 상태 | 프로미스가 생성된 직후 기본 상태 |
| fulfilled | 비동기 처리가 수행된 상태(성공) | resolve 함수 호출 |
| rejected | 비동기 처리가 수행된 상태(실패) | reject 함수 호출 |

**프로미스는 비동기 처리 상태와 처리 결과를 관리하는 객체다.**

### 45.3 프로미스의 후속 처리 메서드

프로미스는 후속 메서드 then, catch, finally를 제공한다. **프로미스의 비동기 처리 상태가 변화하면 후속 처리 메서드에 인수로 전달한 콜백 함수가 선택적으로 호출된다.** 이때 후속 처리 메서드의 콜백 함수에 프로미스의 처리 결과가 인수로 전달된다.

**45.3.1 Promise.prototype.then**

- then 메서드는 2개의 콜백 함수를 인수로 전달받음
- 첫 번째 콜백 함수는 프로미스가 fulfilled 상태(resolve 함수가 호출된 상태)가 되면 호출됨, 이때 콜백 함수는 프로미스의 비동기 처리 결과를 인수로 전달받음
- 두 번째 콜백 함수는 프로미스가 rejected 상태가 되면 호출됨, 이때 콜백 함수는 프로미스의 에러를 인수로 전달받음

then 메서드는 언제나 프로미스를 반환하며 콜백 함수가 프로미스가 아닌 값을 반환하면 그 값을 암묵적으로 resolve 또는 reject 하여 프로미스를 생성해 반환한다

**45.3.2 Promise.prototype.catch**

- 1개의 콜백 함수를 인수로 전달받음
- 프로미스가 rejected 상태인 경우에만 호출됨
- 언제나 프로미스를 반환

**45.3.3 Promise.prototype.finally**

- 한개의 콜백 함수를 인수러 잔달받음
- 프로미스의 성공, 실패와 상관 없이 무조건 한 번 호출됨
- 언제나 프로미스를 반환

### 45.4 프로미스의 에러 처리

```jsx
const wrongUrl = 'https://jsonplaceholder.typicode.com/XXX/1';

// 부적절한 URL로 에러가 발생
promiseGet(wrongUrl).then(
	res => console.log(res),
	err => console.err(err)
); // Error: 404

// catch 사용
promiseGet(wrongUrl)
	.then(res => console.log(res))
	.catch(err => console.error(err));
// Error: 404
```

단 then 메서드의 두 번째 콜백 함수는 첫 번째 콜백 함수에서 발생한 에러를 캐치하지 못하고 코드가 복잡해져 가독성이 좋지 않다. 때문에 then 메서드에 두 번째 콜백 함수를 전달하는 것보다 catch 메서드를 사용하는 것이 가독성이 좋고 명확하다. 에러처리는 catch 메서드에서 하는 것을 권장한다.

### 45.5 프로미스 체이닝

then, catch, finally 후속 처리 메서드는 언제나 프로미스를 반환하므로 연속적으로 호출할 수 있다. 이를 프로미스 체이닝이라 한다.

```jsx
promiseGet(`${url}/posts/1`)
	// 취득한 post의 userId로 user 정보 취득
	.then(({ userId }) => promiseGet(`${url}/users/${userId}`))
	.then(userInfo => console.log(userInfo))
	.catch(err => console.error(err));
```

| 후속 처리 메서드 | 콜백 함수의 인수 | 후속 처리 메서드의 반환값 |
| --- | --- | --- |
| then | promiseGet 함수가 반환한 프로미스가 resolve 한 값(id가 1인 post) | 콜백 함수가 반환한 프로미스 |
| then | 첫 번째 then 메서드가 반환한 프로미스가 resolve한 값(post의 userId로 취득한 user 정보) | 콜백 함수가 반환한 값(undefined)을 resolve한 프로미스 |
| catch
* 에러가 발생하지 않으면 호출되지 않는다. | promiseGet 함수 또는 앞선 후속 처리 메서드가 반환한 프로미스가 reject 한 값 | 콜백 함수가 반환한 값(undefined)을 resolve한 프로미스 |

프로미스는 프로미스 체이닝을 통해 비동기 처리 결과를 전달받아 후속 처리를 하므로 비동기 처리를 위한 콜백 패턴에서 발생하던 콜백 헬이 발생하지 않는다. 다만 프로미스도 콜백 패턴을 사용하므로 콜백 함수를 사용하지 않는 것은 아니다.

콜백 패턴은 가독성이 좋지 않아 ES8에서 도입된 async/await를 통해 해결할 수 있다. 이를 사용하면 프로미스의 후속 처리 메서드 없이 마치 동기 처리처럼 프로미스가 처리 결과를 반환하도록 구현할 수 있다.

```jsx
(async () => {
	const { userId } = await promiseGet(`${url}/posts/1`);
	const userInfo = await promiseGet(`${url}/users/${userId}`);
	console.log(userInfo);
})();
```

### 45.6 프로미스의 정적 메서드

- **Promise.resolve / Promise.reject**
- **Promise.all** 여러 개 비동기 처리를 모두 병렬 처리할 경우 사용, 모든 프로미스가 fulfilled 상태가 되면 모든 처리 결과를 배열에 저장해 새로운 프로미스 반환, 하나라도 rejected 되면 나머지 프로미스가 fulfilled 상태가 되는 것을 기다리지 않고 즉시 종료
- **Promise.race** 프로미스를 요소로 갖는 배열 등의 이터러블을 인수로 전달 받아 가장 먼저 fulfilled 상태가 된 프로미스의 처리 결과를 resolve하는 새로운 프로미스를 반환
- **Promise.allSettled** 프로미스를 요소로 갖는 배열 등의 이터러블을 인수로 전달 받아 전달 받은 프로미스가 모두 settled(비동기 처리가 수행된 상태 fulfilled, rejected)되면 처리 결과를 배열로 반환, ES11(2020)에서 도입, 결과 여부는 상관 없이 처리 결과가 모두 담김

### 45.7 마이크로태스크 큐

```jsx
setTimeout(() => console.log(1), 0);
Promise.resolve()
	.then(() => console.log(2));
	.then(() => console.log(3));

// 2 -> 3 -> 1 출력
```

프로미스의 후속 처리 메서드도 비동기 동작으로 1 → 2 → 3 순으로 출력될 것 처럼 보이지만 2 → 3 → 1 순으로 출력된다. 프로미스 후속 처리 메서드의 콜백 함수는 태스크 큐가 아닌 마이크로태스크 큐에 저장되기 때문

마이크로태스크 큐는 태스크 큐와는 별도의 큐로 프로미스의 후속 처리 메서드의 콜백 함수가 일시 저장된다. 그 외 비동기 함수의 콜백 함수나 이벤트 핸들러는 태스크 큐에 일시 저장된다.

콜백 함수나 이벤트 핸들러를 일시 저장한다는 점에서 태스크 큐와 동일하지만 **마이크로태스크 큐는 태스크큐보다 우선순위가 높다**. 이벤트 루프는 콜 스택이 비면 마이크로태스크 큐 → 태스큐 순으로 실행한다.

### 45.8 fetch

XMLHttpRequest 객체와 마찬가지로 HTTP 요청 전송 기능을 제공하는 클라이언트 사이드 Web API이며 XMLHttpRequest 객체보다 사용법이 간단하고 프로미스를 지원하기 때문에 비동기 처리를 위한 콜백 패턴의 단점에서 자유롭다.

**fetch 함수는 HTTP 응답을 나타내는 Response 객체를 래핑한 Promise 객체를 반환한다.** 

```jsx
const promise = fetch(url [, options])

fetch('https://jsonplaceholder.typicode.com/todos/1')
	.then(response => console.log(response));
```

fetch 함수가 반환하는 프로미스는 기본적으로 404, 500 같은 HTTP 에러가 발생해도 에러를 reject 하지 않고 불리언 타입의 ok 상태를 false로 설정한 Response 객체를 resolve 한다. 오프라인 등의 네트워크 장애나 CORS 에러에 의해 요청이 완료되지 못한 경우에만 프로미스를 reject 한다.

따라서 fetch 함수를 사용할 때는 fetch 함수가 반환한 프로미스가 resolve 한 불리언 타입의 ok 상태를 확인해 명시적으로 에러를 처리할 필요가 있다.

```jsx
fetch(wrongUrl)
	.then(response => {
	if (!response.ok) throw new Error(response.statusText);
	return response.json();
	})
	.then(todo => console.log(todo))
	.catch(err => console.error(err));
```

- **fetch의 GET, POST, PATCH, DELETE**

```jsx
// GET
request.get('')
	.then(res => {
		if (!response.ok) throw new Error(response.statusText);
		return response.json();
	})
	.then(todos => console.log(todos))
	.catch(err => console.log(err));

// POST
request.post('', {
	userId: 1,
	title: 'JavaScript',
	completed: false
}).then(res => {
		if (!response.ok) throw new Error(response.statusText);
		return response.json();
	})
	.then(todos => console.log(todos))
	.catch(err => console.log(err));

// PATCH
request.patch('', {
	completed: true
}).then(res => {
		if (!response.ok) throw new Error(response.statusText);
		return response.json();
	})
	.then(todos => console.log(todos))
	.catch(err => console.log(err));

// DELETE
request.delete('')
	.then(res => {
		if (!response.ok) throw new Error(response.statusText);
		return response.json();
	})
	.then(todos => console.log(todos))
	.catch(err => console.log(err));
```